sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky-take-out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tRe8H5Y7nqDZz8Y5VMo
    access-key-secret: Cx15wtsCDbJ2t1SQY6UPwjJ47jgUdj
    bucket-name: hsj-web127
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxc53d32cbe49227d9
    secret: ec84277b17b624b466a267e3cfe33d80
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://12305e12.r15.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://12305e12.r15.cpolar.top/notify/refundSuccess